### ISSUE TITLE
cabal fails to build and main.hs error and stack error

### ISSUE THREAD

**Issue by 0xameer** [thma/generic-persistence-demo#1]
nix-shell -p ghc cabal-install  stack sqilite 
cabal configure
cabal update  
cabal build

` Compiling Main             ( app/Main.hs, /root/clone/generic-persistence-demo/dist-newstyle/build/x86_64-linux/ghc-9.2.7/generic-persistence-demo-0.1.0.0/x/generic-persistence-demo-exe/build/generic-persistence-demo-exe/generic-persistence-demo-exe-tmp/Main.o )

app/Main.hs:58:13: error:
    Variable not in scope: retrieveById :: Conn -> String -> IO a2
   |
58 |   alice' <- retrieveById @Person conn "123456" 
   |             ^^^^^^^^^^^^

app/Main.hs:62:17: error:
    Variable not in scope: retrieveAll :: Conn -> IO a1
   |
62 |   allPersons <- retrieveAll @Person conn
   |                 ^^^^^^^^^^^

app/Main.hs:69:18: error:
    Variable not in scope: retrieveAll :: Conn -> IO [Person]
   |
69 |   allPersons' <- retrieveAll conn :: IO [Person]
   |                  ^^^^^^^^^^^

app/Main.hs:97:13: error:
    Variable not in scope:
      retrieveById :: Conn -> Int -> IO (Maybe Person)
   |
97 |   alice' <- retrieveById conn (123456 :: Int) :: IO (Maybe Person)
   |             ^^^^^^^^^^^^

app/Main.hs:101:17: error:
    Variable not in scope: retrieveAll :: Conn -> IO [Person]
    |
101 |   allPersons <- retrieveAll conn :: IO [Person]
    |                 ^^^^^^^^^^^

app/Main.hs:108:18: error:
    Variable not in scope: retrieveAll :: Conn -> IO [Person]
    |
108 |   allPersons' <- retrieveAll conn :: IO [Person]
    |                  ^^^^^^^^^^^

app/Main.hs:116:15: error:
    Variable not in scope: retrieveAll :: Conn -> IO [Book]
    |
116 |   allBooks <- retrieveAll conn :: IO [Book]
    |               ^^^^^^^^^^^

app/Main.hs:123:16: error:
    Variable not in scope: retrieveAll :: Conn -> IO [Book]
    |
123 |   allBooks' <- retrieveAll conn :: IO [Book]
    |                ^^^^^^^^^^^

app/Main.hs:174:14: error:
    Variable not in scope: retrieveAll :: Conn -> IO (t0 a0)
    |
174 |   people' <- retrieveAll @Person conn
    |              ^^^^^^^^^^^
Error: cabal: Failed to build exe:generic-persistence-demo-exe from
generic-persistence-demo-0.1.0.0.
Stack error
`DBC-sqlite3            > library file does exist, it may contain errors that are caught by the C`
`

**Comment by thma** [comment]
Hi Sameer,
Thanks for your interest in generic-persistence!

Sorry for the inconvenience with this bug. 
This project generic-persistence-demo is obsolete. Please do not use it any longer.

The Code of the Main.hs file is now part of the extensive test case suite of generic-persistence: https://github.com/thma/generic-persistence/blob/main/test/DemoSpec.hs

The test-suite contains many real world examples and matches the documentation in https://github.com/thma/generic-persistence/blob/main/README.md.

There is also a project https://github.com/thma/servant-gp that works against the latest version of generic-persistence. This showcases a servant based rest service that connects to a database backend via generic-persistence.

I'll deactivate generic-persistence-demo within the next few days to avoid confusion...
